### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by jbonhag** [djrobstep/schemainspect#2] opened 2017-10-06 14:55 UTC
Hi, I ran into this issue running `migra`, but it looked like a `schemainspect` issue so I'm reporting it here.  Please let me know if it would fit better in the other repo.  Thanks for taking a look!

- Python version is 2.7.14, but the same issue occurred with 3.6.3.
- migra version is migra-1.0.1503199248.
- Using brand new pyenv install on Ubuntu.

Running migra:

        $ migra postgresql://user:pass@server1/db postgresql://user:pass@server2/db
        Traceback (most recent call last):
          File "/home/migra/.pyenv/versions/2.7.14/bin/migra", line 11, in <module>
            sys.exit(do_command())
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/migra/command.py", line 73, in do_command
            status = run(args)
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/migra/command.py", line 52, in run
            m = Migration(ac0, ac1)
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/migra/migra.py", line 20, in __init__
            self.changes.i_from = get_inspector(x_from)
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/get.py", line 19, in get_inspector
            return ic(c)
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/pg/__init__.py", line 331, in __init__
            super(PostgreSQL, self).__init__(c, include_internal)
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/inspector.py", line 25, in __init__
            self.load_all()
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/pg/__init__.py", line 342, in load_all
            self.load_deps_all()
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/pg/__init__.py", line 383, in load_deps_all
            'dependents'
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/pg/__init__.py", line 370, in get_related_for_item
            for _ in get_related_for_item(d, att)
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/pg/__init__.py", line 370, in get_related_for_item
            for _ in get_related_for_item(d, att)
          .. repeat 977 more times ..
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/pg/__init__.py", line 367, in get_related_for_item
            return [item.signature] + [
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/pg/__init__.py", line 113, in signature
            return '{}({})'.format(self.quoted_full_name, self.identity_arguments)
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/inspected.py", line 9, in quoted_full_name
            quoted_identifier(self.schema), quoted_identifier(self.name))
          File "/home/migra/.pyenv/versions/2.7.14/lib/python2.7/site-packages/schemainspect/misc.py", line 33, in quoted_identifier
            identifier, remainder = identifier.split('(', 1)
        RuntimeError: maximum recursion depth exceeded

**Comment by djrobstep** [comment] 2017-10-09 05:02
Hey, thanks for reporting this issue! 

This is caused by the dependency detection code for functions, which uses simple string matching to determine the dependencies (we have to resort to this hacky approach because Postgres doesn't track function dependencies directly). 

For instance if `function1` appears on the definition of `function2` then `function1` is assumed to be a dependency of `function2`.

In most cases this works OK, and gives `migra` the power to manage functions better. The downside is you sometimes get problems like this, where there are false positive dependencies detected and you get circular references. We probably need to add some better error handling for this scenario, or the ability to turn off this tracking if desired.

**Comment by jbonhag** [comment] 2017-10-11 20:01
Thanks @djrobstep for getting back to me.  I'll see if I can suss out where the loop is occurring.

Do you think it might be an issue if we're calling a function with the same name, but a different signature?  Like if I'm calling `do_stuff(number, text)` from `do_stuff(number, number)`?

**Comment by djrobstep** [comment] 2017-10-13 18:04
Yes, that is likely where the problem lies: the matching only uses the function name and not the arguments.

There are a few ways to work around this, but none of them are especially elegant. The least worst one is probably to use `migra` from within a python script and manually fix the dependencies in the inspection objects before adding changes.

**Comment by djrobstep** [comment] 2017-10-30 02:39
This should be fixed now. Could you try upgrading your migra installation (make sure schemainspect is migrated too) and see if it now works as expected for you?

**Comment by jbonhag** [comment] 2017-10-30 02:41
Wow, thanks!  Clearly you are more productive on Sunday nights than I am. 😄 I'll check it out in the morning.

**Comment by djrobstep** [comment] 2017-10-30 02:44
My Sunday night productivity tip: Live in Australia, where it's already Monday afternoon ;)

**Comment by jbonhag** [comment] 2018-01-19 17:55
Is it the morning already?  I must have slept a loooong time...

Anyways, thank you @djrobstep -- that fixed the issue.

**Comment by djrobstep** [comment] 2018-01-28 05:07
Awesome, good to know!

**Closed as completed by djrobstep** 2018-01-28 05:07 UTC
